name: Generate Hexo Blog
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Setup hexo environment
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -f
    - name: 安装依赖
      run: |
        rm -rf node_modules
        npm install -g
    - name: Generate pages
      run: |
        hexo generate
        ls -R public/